### ISSUE TITLE
Bogus issue to evaluate workflow

### ISSUE THREAD

**Issue by elijah286** [LabVIEW-DCAF/CVTModule#23]
I am trying to learn how to use Git and this workflow

**Comment by elijah286** [comment]
@pollockm - now that I've created an issue, how do I associated the branch as associated with this issue??

**Comment by pollockm** [comment]
In the commit(s) in that branch that address this issue (or in the PR comments), add a comment with #<number of this issue>, without the <>.  You can close this issue from the commit comments or PR comments by entering fixes #number , and once the PR is approved, the issue will be closed automatically, including a link from this issue to the commit and PR that closed it.

**Comment by pollockm** [comment]
It's actually tricky for me to type in the correct procedure, since it will automatically try to make the linkage.  #twentythree , as a number.

**Comment by pollockm** [comment]
It is also typical to name your branch based on what features/bugs it addresses.  Ideally one branch doesn't address many.  Often it is just one, unless there are a cluster of related issues that are solved as a unit.

**Comment by jacobson3** [comment]
@elijah286 I was going to create another branch for #24 . While I'm here is it okay if I close out this issue and  your active branch so they don't just linger?

**Comment by elijah286** [comment]
Of course! Do what you need to do
